### ISSUE TITLE
Serial1' was not declared in this scope :- Error while compiling example code 

### ISSUE THREAD

**Issue by salmanfarisvp** [RAKWireless/WisLTE_Arduino#1]
System :- **Windows 10 64 bit , 8GB RAM** 
Arduino IDE :-  **1.8.5**
Shield :-  **WisLTE Arduino shield  Quectel BG96 module**
Board :- **Arduino Uno** 

Error while compiling/Uploding example code , 

```

TCP_Client:6: error: '**Serial1' was not declared in this scope**

 #define DSerial Serial1

                 ^

C:\Users\Faris\Documents\Arduino\libraries\WisLTE_Arduino-master\examples\TCP_Client\TCP_Client.ino:20:34: note: in expansion of macro 'DSerial'

 WisLTEBG96TCPIP WisLTE(ATSerial, DSerial);

                                  ^

C:\Users\Faris\Documents\Arduino\libraries\WisLTE_Arduino-master\examples\TCP_Client\TCP_Client.ino: In function 'void setup()':

TCP_Client:6: error: 'Serial1' was not declared in this scope

 #define DSerial Serial1

                 ^

C:\Users\Faris\Documents\Arduino\libraries\WisLTE_Arduino-master\examples\TCP_Client\TCP_Client.ino:23:5: note: in expansion of macro 'DSerial'

     DSerial.begin(115200);

     ^

C:\Users\Faris\Documents\Arduino\libraries\WisLTE_Arduino-master\examples\TCP_Client\TCP_Client.ino: In function 'void loop()':

TCP_Client:6: error: 'Serial1' was not declared in this scope

 #define DSerial Serial1

                 ^

C:\Users\Faris\Documents\Arduino\libraries\WisLTE_Arduino-master\examples\TCP_Client\TCP_Client.ino:66:17: note: in expansion of macro 'DSerial'

                 DSerial.println("\r\nClose Socket Success!");

                 ^

TCP_Client:6: error: 'Serial1' was not declared in this scope

 #define DSerial Serial1

                 ^

C:\Users\Faris\Documents\Arduino\libraries\WisLTE_Arduino-master\examples\TCP_Client\TCP_Client.ino:72:17: note: in expansion of macro 'DSerial'

                 DSerial.println("\r\nSocket Recv Data Success!");

                 ^

TCP_Client:6: error: 'Serial1' was not declared in this scope

 #define DSerial Serial1

                 ^

C:\Users\Faris\Documents\Arduino\libraries\WisLTE_Arduino-master\examples\TCP_Client\TCP_Client.ino:81:17: note: in expansion of macro 'DSerial'

                 DSerial.println("\r\nPlease reconfigure APN!");

                 ^

exit status 1
'Serial1' was not declared in this scope


```

**Comment by salmanfarisvp** [comment]
Compilation is done when I un-comment this code block

```
//#define AT_TX_PIN  11
//#define AT_RX_PIN  10
//SoftwareSerial  DSerial(AT_RX_PIN, AT_TX_PIN);

```

**Comment by so-lu** [comment]
Hi @salmanfarisvp ,
Same issue here. And we also could compile uncommenting that code block. Did the sketch work for you after compiling?
When we un-commented that block, the code didn't do anything (it never got to the point where it writes "This is the WisLTE Debug Serial!").

**Comment by salmanfarisvp** [comment]
Hi @so-lu ,
After un-commenting the code block the compilation is completed so that i can upload my code , but nothing works after uploading , I believe they missed something in the example sketch .

**Comment by xueliu** [comment]
Maybe your Arduino has no Serial1.
GNSS and AT_Debug examples are working in my Arduino 101, but I have to change many parts of source code.

**Comment by salmanfarisvp** [comment]
Hi @xueliu , can you share more deatils about this .

> but I have to change many parts of source code.

**Comment by xueliu** [comment]
Hi @salmanfarisvp, I will commit to my fork ASAP.
> Hi @xueliu , can you share more deatils about this .
> > but I have to change many parts of source code.

**Comment by salmanfarisvp** [comment]
Thank You, and waiting for the merge.

**Comment by salmanfarisvp** [comment]
I have some issues with hologram sim :- https://community.hologram.io/t/socket-error-timed-out-while-using-rak-wis-cellular/2158

**Comment by xueliu** [comment]
> Thank You, and waiting for the merge.

Hello,

It is better to use my fork. https://github.com/xueliu/WisLTE_Arduino/tree/feature/arduino-101

**Comment by salmanfarisvp** [comment]
Problem with Arduino Uno , because Arduino doesn't have a **Serial1**, after using **Software Serial** it's working fine without compilation error . 

**Note** : If you are using Arduino Uno then you must comment the Serial1 and un-comment the SoftwareSerial part . 

**comment** 

`define DSerial Serial1`

**un-comment** 

```
#define AT_TX_PIN  11
#define AT_RX_PIN  10
SoftwareSerial  DSerial(AT_RX_PIN, AT_TX_PIN);
```



Thanks @xueliu @so-lu .

**Comment by humansthatmake** [comment]
> Problem with Arduino Uno , because Arduino doesn't have a **Serial1**, after using **Software Serial** it's working fine without compilation error .
> 
> **Note** : If you are using Arduino Uno then you must comment the Serial1 and un-comment the SoftwareSerial part .
> 
> **comment**
> 
> `define DSerial Serial1`
> 
> **un-comment**
> 
> ```
> #define AT_TX_PIN  11
> #define AT_RX_PIN  10
> SoftwareSerial  DSerial(AT_RX_PIN, AT_TX_PIN);
> ```
> Thanks @xueliu @so-lu .

If you want to see the debug messages on your serial monitor switch ATSerial for DSerial and vice-versa.

```
//#define DSerial Serial1
#define DSerial Serial
#define AT_TX_PIN  11
#define AT_RX_PIN  10
SoftwareSerial  ATSerial(AT_RX_PIN, AT_TX_PIN);
```
and 

`WisLTEBG96TCPIP WisLTE(DSerial, ATSerial);`
